---
- name: Install SASL
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - libsasl2-modules
    - libsasl2-modules-sql
    - libgsasl7
    - libauthen-sasl-cyrus-perl
    - sasl2-bin
    - libpam-mysql

- name: Add the postfix user to the sasl group
  user: name=postfix group=sasl append=yes

- name: Create SASL directory
  file: path=/var/spool/postfix/var/run/saslauthd state=directory recurse=yes

- name: Toggle SASL
  replace: dest=/etc/default/saslauthd regexp="^START=.*$" replace="START=yes"
  notify: Restart saslauthd

- name: Tweak SASL opts
  replace: dest=/etc/default/saslauthd regexp="^OPTIONS=\".*\"" replace="OPTIONS=\"-r -c -m /var/spool/postfix/var/run/saslauthd\""

- name: Install the smtpd conf file
  template: src=postfix_smtpd.conf.j2 dest=/etc/postfix/sasl/smtpd.conf

- name: Install the pam.d smtp file
  template: src=postfix_pamd_smtp.j2 dest=/etc/pam.d/smtp
  notify:
    - Restart saslauthd
    - Restart postfix
